# Generated by Django 5.1.2 on 2024-11-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='informacion',
            field=models.TextField(null=True),
        ),
    ]
